name: Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - support/apollo-2

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'build: releasing version') != true"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8

      - name: Cache Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build
        run: mvn --no-transfer-progress -B -U --file pom.xml install
